version: '3.8'

services:
  postgres:
    # PostgreSQL 15.5 - 안정적인 프로덕션 버전
    image: postgres:15.5
    environment:
      POSTGRES_DB: issue_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 컨테이너 이름 지정
    container_name: rss_postgres
    # 리소스 제한
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    # Redis 7.2 - Alpine Linux 기반 (경량)
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # 컨테이너 이름 지정
    container_name: rss_redis

    # Redis 설정
    # 메모리 사용량이 256MB에 도달하면
    # 가장 오래전에 사용된 키부터 자동 삭제
    # 새로운 작업 큐는 계속 추가 가능
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    # 리소스 제한
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres_data:
  redis_data: 