# Generated by Django 4.2.7 on 2025-07-31 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="피드 제목")),
                ("url", models.URLField(unique=True, verbose_name="RSS URL")),
                ("description", models.TextField(blank=True, verbose_name="피드 설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "last_crawled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 크롤링 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS 피드",
                "verbose_name_plural": "RSS 피드들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RSSProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "성공"),
                            ("error", "오류"),
                            ("partial", "부분 성공"),
                        ],
                        max_length=10,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "entries_processed",
                    models.IntegerField(default=0, verbose_name="처리된 엔트리 수"),
                ),
                (
                    "entries_new",
                    models.IntegerField(default=0, verbose_name="새로운 엔트리 수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="처리 시간(초)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="rss_crawler.rssfeed",
                        verbose_name="RSS 피드",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS 처리 로그",
                "verbose_name_plural": "RSS 처리 로그들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RSSEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("link", models.URLField(verbose_name="링크")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "author",
                    models.CharField(blank=True, max_length=200, verbose_name="작성자"),
                ),
                ("published_at", models.DateTimeField(verbose_name="발행일")),
                (
                    "keywords",
                    models.TextField(blank=True, default="[]", verbose_name="키워드"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="요약")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="처리 완료"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="rss_crawler.rssfeed",
                        verbose_name="RSS 피드",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS 엔트리",
                "verbose_name_plural": "RSS 엔트리들",
                "ordering": ["-published_at"],
                "unique_together": {("feed", "link")},
            },
        ),
    ]
